name: Deploy site
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Cache stuff
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 21
      - name: Run lint
        id: lint
        run: npm run lint
      - name: Build site
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: built-site
          path: dist
  prepare_site:
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: built-site
          path: _site
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
  pages_deploy:
    needs: prepare_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
